### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by hadasApplied** [babelomics/SMAca#7]
Hi, great tool, thanks!
Any way to get it up and running on Windows 10 (no WSL or Linux VM solutions)?
Thanks

**Comment by dlopez-bioinfo** [comment]
The tools has been tested only on linux platforms. However, as far as I know, it does not contain linux specific code. Since the installation depends on conda, it may work on windows and MAC as well

**Comment by hadasApplied** [comment]
Thanks.
I've managed to get it running on [bamnostic](http://bamnostic.readthedocs.io) instead of pysam
